### ISSUE TITLE
你好 冒昧的打扰下

### ISSUE THREAD

**Issue by Weststreet** [ziyouchutuwenwu/protobuf_demo#1]
![image](https://cloud.githubusercontent.com/assets/11329810/23303703/980a950a-fad0-11e6-8e65-154bb3805712.png)
请问你还记得这个问题么？后来是如何解决的呢？我现在也遇到了相同的问题

**Comment by ziyouchutuwenwu** [comment]
居然找到这里来了……pfpf
当时我直接联系子龙山人大神，大神看了以后，发现是2dx集成的websocket组件的版本问题，后来修好了，现在具体不清楚
